### ISSUE TITLE
Feature Request - Block1 RAM toggle

### ISSUE THREAD

**Issue by dspiteri** [MiSTer-devel/VIC20_MiSTer#11]
As it says, it would be useful to be able to toggle block1 $2000 RAM independently of 2/3 to avoid the memory map reconfig for 8K. This is helpful for Scott Adams games, maybe others. I suggest adding to the current cycle.

BLK1 -> BLK1+2 -> BLK1+2+3 -> **BLK2+3**.

**Comment by sorgelig** [comment]
i've added more flexible setting

**Comment by dspiteri** [comment]
Works well, thanks!
