### ISSUE TITLE
MegaCart menu only loads / runs with video mode set to PAL not NTSC

### ISSUE THREAD

**Issue by RetroInVitro** [MiSTer-devel/VIC20_MiSTer#12]
With NTSC selected, the screen is just white.

**Comment by sorgelig** [comment]
Core has no relation to this if i understood right. Probably Megacart is PAL-only.

**Comment by RetroInVitro** [comment]
> Core has no relation to this if i understood right. Probably Megacart is PAL-only.

Thank you for the quick response.  

No, the MegaCart supports both PAL and NTSC.  I've used it on real VIC-20 in N.America.   

http://www.retroisle.com/commodore/vic20/Articles/megacart.php

**Comment by sorgelig** [comment]
ok. i will check.

**Comment by beamrider66** [comment]
Could be related to this...

https://misterfpga.org/viewtopic.php?p=38633&hilit=vic+20+ntsc+timing#p38633

Seems that it went wrong after the sound fix...

**Comment by RetroInVitro** [comment]
>  Pretty sure this is fixed.

@sorgelig  Just checked and yeahhhhhh!!!   Thank you for fixing this.   Another childhood adjacent system down!
