### ISSUE TITLE
NTSC analog video output is broken

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/VIC20_MiSTer#13]
Latest release (20221201) broke NTSC video output through Analog IO board. When set to PAL the core displays as expected, but NTSC video is completely red. Consumer CRT TV connected with a VGA-SCART cable.
![VIC20_20221201](https://user-images.githubusercontent.com/70150033/205136205-9a009113-cd33-470e-8b03-8cae4160f693.jpg)
Despite the obvious issue, Megacart now loads properly when core is set to NTSC.

**Comment by dspiteri** [comment]
NTSC colour on CRT is OK for me, the screen is offset to the left though like on your display.

**Comment by Thelypody** [comment]
Checked the core again to be sure it was not a random fluke, but NTSC output is still broken on my end. It appears not to be always red though, shuffling though random cartridges I found that Frogger makes the screen yellow, Q*Bert makes it green, Bank Robber makes it blue, etc. Megacart dims the whole screen black and makes OSD menu completely unreadable. Star Battle surprisingly displays with proper colors but the image is indeed shifted to the left.

**Comment by dspiteri** [comment]
![PXL_20221202_060126264](https://user-images.githubusercontent.com/19847868/205226492-d39c8b35-71ed-4c75-82f0-41f387c65a90.jpg)

This is how it looks for me. The colour is OK (component) but the offset is the same as yours.

**Comment by sorgelig** [comment]
Probably sync/blank signals aren't correct. I've used HDMI to test.
I will see VGA output.. need to use my VGA->HDMI converter..

**Comment by sorgelig** [comment]
try this build:
[VIC20.zip](https://github.com/MiSTer-devel/VIC20_MiSTer/files/10143929/VIC20.zip)

**Comment by Thelypody** [comment]
The attached build displays without issues, I've successfully played a bit with the Megacart in NTSC mode. Thanks for fast response.

**Comment by dspiteri** [comment]
> try this build:

Confirming that fixed the issue too. Thanks sorgelig!
