### ISSUE TITLE
sound distortion

### ISSUE THREAD

**Issue by nippur72** [MiSTer-devel/VIC20_MiSTer#5]
the VIC20 core apparently has a sound distortion, we discussed that on the [Denial forum](http://sleepingelephant.com/ipw-web/bulletin/bb/viewtopic.php?f=14&t=9320&start=15#p109730).

I forked a debug version of the core, I've bypassed the VIC20 digital filters (lowpass and highpass) and the linux audio mixer, so the audio output of the 6561 goes directly into the DAC audio output. With such bypass the audio is no longer distorted. 

But but unfortunately I don't know much of the MiSTer architecture yet (I'm coming from MiST), so it's better someone more experienced than me does the fix. I've reported it here so it's easier to locate the issue.

**Comment by dev31337** [comment]
Hi,

Is it possible to make a new release of the core (with your commit) so we can test your sound fix ?

Regards.

**Comment by nippur72** [comment]
@dev31337 my commit is just an hack that bypasses the sound mixer so it's not worth making a release for it. (I hope some more experienced developer steps in and fix it).

Anyway if you want to test the resulting .rbf file, you can get it from [here](https://drive.google.com/file/d/1Hf5ZMUx87MNQWNB_cU4bfg1tH7gZ3iRI/view?usp=sharing) from my gdrive.

**Comment by verm71** [comment]
I confirm that nippur72's build from July 26 posted here http://sleepingelephant.com/ipw-web/bulletin/bb/viewtopic.php?f=14&t=9320&start=15#p109712 fixes the issue, while the subsequent test of July 28th further down the the same forum shows the distortion again. The latest official build here ("Release 20210121") also shows the issue. The issue appears to be narrowed down to the filters.

**Comment by sorgelig** [comment]
try this version:
[VIC20.zip](https://github.com/MiSTer-devel/VIC20_MiSTer/files/5878338/VIC20.zip)

**Comment by verm71** [comment]
Yes, that one sounds great. My go-to test is usually Commodore's Draw Poker, because you know right from the start if the sound is ok or not.

**Comment by verm71** [comment]
The latest Release 20210130 fixes the problem for me. I'll keep testing with other programs, but so far it passes the Draw Poker test.
